ALTER DATABASE jwp_jdbc DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `survey_results_public` (
  `Respondent` int(11) DEFAULT NULL,
  `Hobby` VARCHAR(64),
  `OpenSource` text,
  `Country` text,
  `Student` VARCHAR(64),
  `Employment` text,
  `FormalEducation` text,
  `UndergradMajor` text,
  `CompanySize` text,
  `DevType` text,
  `YearsCoding` text,
  `YearsCodingProf` text,
  `JobSatisfaction` text,
  `CareerSatisfaction` text,
  `HopeFiveYears` text,
  `JobSearchStatus` text,
  `LastNewJob` text,
  `AssessJob1` text,
  `AssessJob2` text,
  `AssessJob3` text,
  `AssessJob4` text,
  `AssessJob5` text,
  `AssessJob6` text,
  `AssessJob7` text,
  `AssessJob8` text,
  `AssessJob9` text,
  `AssessJob10` text,
  `AssessBenefits1` text,
  `AssessBenefits2` text,
  `AssessBenefits3` text,
  `AssessBenefits4` text,
  `AssessBenefits5` text,
  `AssessBenefits6` text,
  `AssessBenefits7` text,
  `AssessBenefits8` text,
  `AssessBenefits9` text,
  `AssessBenefits10` text,
  `AssessBenefits11` text,
  `JobContactPriorities1` text,
  `JobContactPriorities2` text,
  `JobContactPriorities3` text,
  `JobContactPriorities4` text,
  `JobContactPriorities5` text,
  `JobEmailPriorities1` text,
  `JobEmailPriorities2` text,
  `JobEmailPriorities3` text,
  `JobEmailPriorities4` text,
  `JobEmailPriorities5` text,
  `JobEmailPriorities6` text,
  `JobEmailPriorities7` text,
  `UpdateCV` text,
  `Currency` text,
  `Salary` text,
  `SalaryType` text,
  `ConvertedSalary` text,
  `CurrencySymbol` text,
  `CommunicationTools` text,
  `TimeFullyProductive` text,
  `EducationTypes` text,
  `SelfTaughtTypes` text,
  `TimeAfterBootcamp` text,
  `HackathonReasons` text,
  `AgreeDisagree1` text,
  `AgreeDisagree2` text,
  `AgreeDisagree3` text,
  `LanguageWorkedWith` text,
  `LanguageDesireNextYear` text,
  `DatabaseWorkedWith` text,
  `DatabaseDesireNextYear` text,
  `PlatformWorkedWith` text,
  `PlatformDesireNextYear` text,
  `FrameworkWorkedWith` text,
  `FrameworkDesireNextYear` text,
  `IDE` text,
  `OperatingSystem` text,
  `NumberMonitors` text,
  `Methodology` text,
  `VersionControl` text,
  `CheckInCode` text,
  `AdBlocker` text,
  `AdBlockerDisable` text,
  `AdBlockerReasons` text,
  `AdsAgreeDisagree1` text,
  `AdsAgreeDisagree2` text,
  `AdsAgreeDisagree3` text,
  `AdsActions` text,
  `AdsPriorities1` text,
  `AdsPriorities2` text,
  `AdsPriorities3` text,
  `AdsPriorities4` text,
  `AdsPriorities5` text,
  `AdsPriorities6` text,
  `AdsPriorities7` text,
  `AIDangerous` text,
  `AIInteresting` text,
  `AIResponsible` text,
  `AIFuture` text,
  `EthicsChoice` text,
  `EthicsReport` text,
  `EthicsResponsible` text,
  `EthicalImplications` text,
  `StackOverflowRecommend` text,
  `StackOverflowVisit` text,
  `StackOverflowHasAccount` text,
  `StackOverflowParticipate` text,
  `StackOverflowJobs` text,
  `StackOverflowDevStory` text,
  `StackOverflowJobsRecommend` text,
  `StackOverflowConsiderMember` text,
  `HypotheticalTools1` text,
  `HypotheticalTools2` text,
  `HypotheticalTools3` text,
  `HypotheticalTools4` text,
  `HypotheticalTools5` text,
  `WakeTime` text,
  `HoursComputer` text,
  `HoursOutside` text,
  `SkipMeals` text,
  `ErgonomicDevices` text,
  `Exercise` text,
  `Gender` text,
  `SexualOrientation` text,
  `EducationParents` text,
  `RaceEthnicity` text,
  `Age` text,
  `Dependents` text,
  `MilitaryUS` text,
  `SurveyTooLong` text,
  `SurveyEasy` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8

ALTER TABLE survey_results_public
ADD INDEX `hobby` (`Student` ASC, `Hobby` ASC) VISIBLE;

-- new table
CREATE TABLE IF NOT EXISTS `jwp_jdbc`.`new_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DevType` VARCHAR(45) NOT NULL,
  `YearsCodingProf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

INSERT INTO new_table (DevType, YearsCodingProf)
SELECT substring_index(substring_index(DevType, ';', sequence.seq_num), ';', -1),
        substring_index(substring_index(YearsCodingProf, ' ', 1), '-', 1)
FROM survey_results_public
JOIN SEQUENCE_OF_JOB as sequence
ON sequence.seq_num <= CHAR_LENGTH(DevType) - CHAR_LENGTH(REPLACE(DevType, ';', '')) + 1;

DROP TABLE IF EXISTS `jwp_jdbc`.`new_table`;